#ifndef LIBPIGA_PIGA_DEFINITIONS_HPP_INCLUDED
#define LIBPIGA_PIGA_DEFINITIONS_HPP_INCLUDED

#define PIGA_DEBUG_PRESTRING "[PiGa] "

#define PIGA_MAJOR_VERSION 0
#define PIGA_MINOR_VERSION 2
#define PIGA_MINI_VERSION 0

#endif
